# Generated by Django 4.0.3 on 2022-03-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['grade'], 'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
    ]
